alice:
    image: redtcd
    command: >
        /usr/bin/coind -regtest
        -conf=/btc/coin.conf -datadir=/btc/data
        -addnode=seeda:12333 -addnode=seedb:12333 -rpcallowip=172.17.1.0/24
    expose:
        - "12333"
        - "12332"
    ports:
        - "12333:12333"
        - "12332:12332"
    links:
        - seeda
        - seedb

bob:
    image: redtcd
    command: >
        /usr/bin/coind -regtest
        -conf=/btc/coin.conf -datadir=/btc/data
        -addnode=seeda:12333 -rpcallowip=172.17.1.0/24
    expose:
        - "12333"
        - "12332"
    links:
        - seeda

seeda:
    image: redtcd
    command: >
        /usr/bin/coind -regtest -txindex -disablewallet
        -conf=/btc/coin.conf -datadir=/btc/data
        -rpcallowip=172.17.1.0/24
    expose:
        - "12333"
        - "12332"

seedb:
    image: redtcd
    command: >
        /usr/bin/coind -regtest -txindex -disablewallet
        -conf=/btc/coin.conf -datadir=/btc/data
        -rpcallowip=172.17.1.0/24
    expose:
        - "12333"
        - "12332"

pycoin:
    build: pycoin
    command: /bin/true

bitcore:
    build: bitcore
    command: /bin/true

test:
    hostname: test
    image: y12docker/apbase:1504
    command: nosetests -v /app/test_http.py
    volumes:
        - testapp/:/app
    links:
        - alice
        - bob
        - seeda
