bitcoind:
    build: bitcoind
    command: /bin/true

# bitcoind with build-essential
bitcoindbe:
    build: bitcoindbe
    command: /bin/true

loges:
    build: loges
    command: logstash agent -f /loges/bitcoin-search.conf
    ports:
        - "9200:9200"

alice:
    image: bitreg_bitcoind
    links:
        - seeda
        - seedb
    environment:
        BITCOIND_PARAM: -regtest
        BITCOIN_CONF: addnode=seeda\naddnode=seedb

bob:
    image: bitreg_bitcoind
    links:
        - seeda
        - seedb
    environment:
        BITCOIND_PARAM: -regtest
        BITCOIN_CONF: addnode=seeda\naddnode=seedb

bcp2p:
    build: bcp2p
    links:
        - alice
    environment:
        LINK_HOST: alice

bcnode:
    build: bcnode
    links:
        - seeda
    environment:
        BITCOIND_PARAM: -regtest -txindex -addnode=seeda


seeda:
    image: bitreg_bitcoind
    environment:
        BITCOIND_PARAM: -regtest -txindex


seedb:
    image: bitreg_bitcoind
    environment:
        BITCOIND_PARAM: -regtest -txindex
