bitcoind:
    build: bitcoind
    command: /bin/true

# bitcoind with build-essential
bitcoindbe:
    build: bitcoindbe
    command: /bin/true

alice:
    image: bitreg_bitcoind
    links:
        - seeda
        - seedb
    environment:
        BITCOIND_PARAM: -regtest
bob:
    image: bitreg_bitcoind
    links:
        - seeda
        - seedb
    environment:
        BITCOIND_PARAM: -regtest

bcp2p:
    build: bcp2p
    links:
        - alice

bcnode:
    build: bcnode
    links:
        - seeda
    environment:
        BITCOIND_PARAM: -regtest -txindex


seeda:
    image: bitreg_bitcoind
    environment:
        BITCOIND_PARAM: -regtest -txindex


seedb:
    image: bitreg_bitcoind
    environment:
        BITCOIND_PARAM: -regtest -txindex
