alice:
    build: .
    command: bitcoind -regtest
    links:
        - seed1
        - seed2

bob:
    build: .
    command: bitcoind -regtest
    links:
        - seed1
        - seed2

nred:
    build: nodeapp
    command: static
    links:
        - bob

seed1:
    build: .
    command: bitcoind -regtest -txindex

seed2:
    build: .
    command: bitcoind -regtest -txindex
