rbase:
    build: rbase
    command: /bin/true

bitcoind:
    build: bitcoind
    command: /bin/true

# bitcoind with build-essential
bitcoindbe:
    build: bitcoindbe
    command: /bin/true

loges:
    build: loges
    command: logstash agent -f /loges/bitcoin-search.conf
    ports:
        - "9200:9200"

alice:
    image: bitreg_bitcoind
    links:
        - seeda
        - seedb
    environment:
        BITCOIND_PARAM: -regtest
        BITCOIN_CONF: addnode=seeda:12333\naddnode=seedb:12333\nrpcallowip=172.17.0.0/24\n

bob:
    image: bitreg_bitcoind
    links:
        - seeda
        - seedb
    environment:
        BITCOIND_PARAM: -regtest
        BITCOIN_CONF: addnode=seeda:12333\naddnode=seedb:12333\nrpcallowip=172.17.0.0/24\n

miner:
    image: bitreg_bitcoind
    links:
        - seeda
    environment:
        BITCOIND_PARAM: -regtest
        BITCOIN_CONF: addnode=seeda:12333\nrpcallowip=172.17.0.0/24\n

gcmt:
    build: gcmt
    links:
        - alice
        - bob
        - miner

bcp2p:
    build: bcp2p
    links:
        - alice
    environment:
        LINK_HOST: alice
        LINK_PORT: 12333

bcnode:
    build: bcnode
    links:
        - seeda
    environment:
        BITCOIND_PARAM: -regtest -txindex -addnode=seeda:12333


seeda:
    image: bitreg_bitcoind
    environment:
        BITCOIND_PARAM: -regtest -txindex -disablewallet

seedb:
    image: bitreg_bitcoind
    environment:
        BITCOIND_PARAM: -regtest -txindex -disablewallet
