bitcoind:
    build: bitcoind
    command: /bin/true

alice:
    image: bitreg_bitcoind
    links:
        - seeda
        - seedb
    environment:
        BITCOIND_PARAM: -regtest
bob:
    image: bitreg_bitcoind
    links:
        - seeda
        - seedb
    environment:
        BITCOIND_PARAM: -regtest

nred:
    build: nodeapp
    links:
        - bob

seeda:
    image: bitreg_bitcoind
    environment:
        BITCOIND_PARAM: -regtest -txindex


seedb:
    image: bitreg_bitcoind
    environment:
        BITCOIND_PARAM: -regtest -txindex
