alias dc='docker-compose -p bluetc'
alias dcup='dc stop && dc build && dc up -d'
alias rbasesh='docker run -i -t bluetc_rbase bash'
alias rmakesh='docker run -i -t bluetc_rmake bash'
alias alicesh='docker exec -i -t bluetc_alice_1 bash'
