alias dc='docker-compose -p bluetc'
alias bi='cd xbutcd && chmod +x install.sh && ./install.sh && cd ..'
alias bb='cd xbutcd && chmod +x build.sh && ./build.sh && cd ..'
alias dcup='dc stop && dc build && dc up -d'
alias butcdsh='docker run -i -t bluetc_butcd /bin/bash'
alias alicesh='docker exec -i -t bluetc_alice_1 bash'
